name: monitoreo_medios
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pandas
  - feedparser
  - pyyaml
  - matplotlib
  - jupyter
  - sqlite
  - pytorch
  - pip
  - pip:
    - transformers
    - streamlit
    - python-dotenv
    - pytest
